name: static code analysis

on:
  workflow_run:
    workflows: ['Build']
    branches: ['main', 'develop']
    type:
      - completed

jobs:
  SonarCloud Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
